### ISSUE TITLE
Not working update 26.2

### ISSUE THREAD

**Issue by Manueelite** [Ferrster/Snowrunner-Manual-Gearbox-Mod#11]
Please update to patch 26.2 / Season 11: Lights & Cameras.

Thank You for this.

**Comment by Ferrster** [comment]
Working on it. It seems this update introduced some significant code changes. It may take a bit longer than usual to update.

**Comment by Ferrster** [comment]
[Done](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.4)
