### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by Swarckoph** [Ferrster/Snowrunner-Manual-Gearbox-Mod#15]
Please update the patch to 27.0

Thank you for this.

**Comment by Ferrster** [comment]
Hi! Thanks! Didn't have time to fix it yesterday, hopefully I can fix it today

**Comment by Ferrster** [comment]
[Fixed](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.5), sorry for the delay
