### ISSUE TITLE
crashing on patch 27

### ISSUE THREAD

**Issue by Levaithan-71** [Ferrster/Snowrunner-Manual-Gearbox-Mod#16]
The mod is crashing the game or going in a loop state after they released a patch note recently, is this happening on your end too?
![Screenshot 2023-11-24 040209](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/assets/151877855/b0413665-7ee8-4a30-b71e-4d07737d141b)

**Comment by Ferrster** [comment]
Hi! Yes, every new patch the mod breaks, so I have to patch it. Didn't have time to fix it yesterday, hopefully I can fix it today

**Comment by Levaithan-71** [comment]
Thank you so much for your effort.

**Comment by RaMaNy4** [comment]
THX, you do greatest work!
