### ISSUE TITLE
Not working with 1/31/24 DLC

### ISSUE THREAD

**Issue by LordVerminaard** [Ferrster/Snowrunner-Manual-Gearbox-Mod#17]
I know it's stating the obvious but the mod isn't working with the season 12 DLC released 1/31/24, I am just adding so that I know when it is updated. :)

Thanks!

**Comment by juicyfloops** [comment]
i'd also like to plead work on an update, with deepest gratitude for a result

**Comment by Funky-Punky** [comment]
In the meantime, you can just downgrade your game to get the mod working again. I had no problems at all doing that.

https://www.makeuseof.com/how-to-downgrade-steam-games/
https://steamcommunity.com/sharedfiles/filedetails/?id=1086279994

**Comment by lonewolf0708** [comment]
What about those who own on a different platform like Epic?

**Comment by MisterNoNameLP** [comment]
> In the meantime, you can just downgrade your game to get the mod working again. I had no problems at all doing that.
> 
> https://www.makeuseof.com/how-to-downgrade-steam-games/ https://steamcommunity.com/sharedfiles/filedetails/?id=1086279994

OHH thanks god! Im looking for an reliable way to prevent steam from updating a game since ages now and not even thought of downgrading as an potential way.
And now there is a solution that is even better as an simple update prevention.
U just made a life a little brighter dude! :)

**Comment by MisterNoNameLP** [comment]
> What about those who own on a different platform like Epic?

Does not seem to be possible unfortunately :/

**Comment by Ferrster** [comment]
Sorry for the delay guys(. Updated for new patch (https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.6)

**Comment by Zeroykaa** [comment]
> Sorry for the delay guys(. Updated for new patch (https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.6)

The game in Epic Games Stores has been updated again, is it possible to update the mod?
