### ISSUE TITLE
UPDATE 28.2 PLEASE

### ISSUE THREAD

**Issue by MazerUNKNOW** [Ferrster/Snowrunner-Manual-Gearbox-Mod#18]

**Comment by Stepanuch96** [comment]
Тоже надо обновления.

**Comment by Ferrster** [comment]
[Done!](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.8)

**Comment by PremmanQC** [comment]
> [Done!](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.8)

THANK YOU!!! I have created an account just to say that! Without your mod I just can't play the game anymore!! 

And lesson learned i turned off that pesky auto-update lmao

**Comment by Ferrster** [comment]
Thank you! Glad you enjoy it! @PremmanQC

**Comment by PremmanQC** [comment]
Hi @Ferrster ... even with auto-update off those as*h**le updated the game automatically to 29.0... starting to have genuine hate for that auto update lol... can we get an update for the code please? Thank you and no rush friend

**Comment by Zinger201678** [comment]
обновите пожалуйста кпп

**Comment by RixClash** [comment]
Обновите пожалуйста! Нет больше сил нажимать шифт что бы заставить эту чертову коробку переключаться вовремя! Обязуюсь выключить автоматическое обновление!

**Comment by Zinger201678** [comment]
ИГРА ВЫЛЕТАЕТ у меня стим версяи
