### ISSUE TITLE
v0.1.8 shows up as v0.1.7 and does not work

### ISSUE THREAD

**Issue by jacoobls** [Ferrster/Snowrunner-Manual-Gearbox-Mod#20]
What the title says. The latest version shows up as "v0.1.7" in the cmd when it is running, and the game does not recognize any inputs nor any inputs are being listed in the console.

**Comment by jacoobls** [comment]
Uhh, interesting. I downloaded other versions just to test if by any chance you just did not update it to write out 0.1.8 instead of 0.1.7, and sure enough version 0.1.6 shows up as 0.1.4. OK, but the weird thing: v0.1.6 works on the latest game version somehow. So, issue solved I guess?

So if the latest version does not work for anyone else for some reason, just use v0.1.6 for now, that one works somehow.

**Comment by Ferrster** [comment]
@jacoobls Yeah, I sometimes forget to change the version, bc I have to do it manually. Hopefully I'll find more reliable way to change displayed version.
