### ISSUE TITLE
Im sry but i can get it to work

### ISSUE THREAD

**Issue by NiklasNiko** [Ferrster/Snowrunner-Manual-Gearbox-Mod#23]
Added it to the folder where SR.exe is located started the game launched smgm loader and just before the game finishes it crashes.
- tried run as admin
- already in game 
- clean install
- unmodded
- fullscreen and windowed
- deleting the controll file
Im on windows 11 if somebody tells me where the crashfile is located i can provide it.
Just noticed it doesnt create an INI file anymore + should all the line in the window be empty after " : " ? was always like this

**Comment by Ferrster** [comment]
@NiklasNiko
1. What version of a game are you running (Steam, EGS)?
1. What version of the mod you tried to run on what game patch?

**Comment by NiklasNiko** [comment]
Steam and newest verion 0.1.9

**Comment by Ferrster** [comment]
Can you please send me your SnowRunner.exe file so I can look into it? You can use this service: https://dropmefiles.com

**Comment by NiklasNiko** [comment]
https://dropmefiles.com/ui6Vz

Hope this is right. keep in mind my game is now modded if its important.

**Comment by NiklasNiko** [comment]
Dont know how to close/delete this. reinstalled windows and out of the blue works perfectly. still thank you VERY much for you help.
