### ISSUE TITLE
1 gear instead of low+

### ISSUE THREAD

**Issue by MOOOOs** [Ferrster/Snowrunner-Manual-Gearbox-Mod#26]
is there a way to make it shift into first instead of low+ when truck has low gears? i have separate controls for all lows

**Comment by Ferrster** [comment]
Technically, Low+ is the same as first gear. If you put on a different gearbox that doesn't have lows, it'll show that you are in first gear

**Comment by MOOOOs** [comment]
ah ok i forgot L+ is same ratio as first gear and probably makes more sense to have lockable diff at first gear :) wish game had Low/High ratio switch instead of this unreasitic mess. Thanks for this awesome mod it atleast gives manual gearbox :)
