### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by FluffierKittens** [Ferrster/Snowrunner-Manual-Gearbox-Mod#3]
Hello! Not an issue with the mod, but rather a licensing question. I've heavily relied on your code to create a similar DLL that leaves most gear changes alone and only disables auto-reverse. This includes, but is not limited to, wholesale copying of data_types.h.

Are you releasing SMGM under any particular license, e.g. GPL or MIT? And regardless, would you have a problem with me publicly releasing my own derivative mod? 

Thanks for all your hard work on this one!

**Comment by Ferrster** [comment]
Hello. This project is licensed under the MIT license. I added an appropriate LICENSE file (im still an amateur at these things, sorry).
And no, I wouldn't have any problem with you using any parts of my code. You can do whatever you want with it.
