### ISSUE TITLE
Update please

### ISSUE THREAD

**Issue by MOOOOs** [Ferrster/Snowrunner-Manual-Gearbox-Mod#30]
new update that brings one paid car broke this mod

**Comment by ASchlecker** [comment]
yes! this would be greatly appreciated 🙂🌈

**Comment by MOOOOs** [comment]
I may even try to make patch myself but idk where to start and what needs to be changed. I guess nothing much changed only Version number

**Comment by ASchlecker** [comment]
haha yeah, no idea what to change/ what causes the game to crash 🤷‍♂️

**Comment by MOOOOs** [comment]
yes looks like those values change every patch if i knew how to find those values in sr i would have done it by now :D

**Comment by Funky-Punky** [comment]
Yeah, the values that change every time are to pointers to functions within the compiled SnowRunner.exe file.
Unfortunately they cant be extracted from the game UI and a program that scans the processes memory (like Cheat Engine) is required.

The process is actually quite straightforward, but the fewer you know about programming and snowrunner, the more you are fucked if something goes wrong.

If you look at the older issues, you can see that i talked to @Ferrster and he told me a little bit about the project in private.
I tried to extract the new values yesterday, but got stuck on one.
Seems like we once again need the master himself to help us out of this one :/

**Comment by MOOOOs** [comment]
I got Cheat Engine can you tell me procedure of how to get those memory values in cheat engine i have used it before know some

**Comment by ASchlecker** [comment]
sounds good, sounds good. did you get it to work properly, or not? : )

**Comment by MOOOOs** [comment]
no i haven't got answer from him on telegram which values and how to get those values so these may be useless

**Comment by Funky-Punky** [comment]
@MOOOOs If you want, we can also connect and share what we got. If you use discord, add me with my username massimolongo.

**Comment by MOOOOs** [comment]
Can't find user with that name

**Comment by Funky-Punky** [comment]
Huh, weird - what's your username?
