### ISSUE TITLE
Crash Dump Sending Utility "Application has stopped working"

### ISSUE THREAD

**Issue by Ymran09** [Ferrster/Snowrunner-Manual-Gearbox-Mod#31]
Help me please. Hi, I would really like to play the game with this mod. But I have a problem with the mod.
After launching the game and activating the mod and then launching the game, the game gives me an error:
![IMG_20240803_153951](https://github.com/user-attachments/assets/0ec99e60-489a-490a-8d99-7088d9852703)

**Comment by Ymran09** [comment]
-I installed the latest version of the mod(v0.1.10)
-I have the cracked version of the game (elamigos)
-I have installed all C++ visuals

**Comment by Funky-Punky** [comment]
The game update a few days ago broke the mod. You will either have to wait for a mod update or downgrade your game.
See issue #30

**Comment by Ymran09** [comment]
> La mise à jour du jeu il y a quelques jours a cassé le mod. Vous devrez soit attendre une mise à jour du mod, soit rétrograder votre jeu. Voir le problème [n°30](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/issues/30)
