### ISSUE TITLE
Version 32.0

### ISSUE THREAD

**Issue by TsengoHUN** [Ferrster/Snowrunner-Manual-Gearbox-Mod#37]
Hi

Just to let you know, version 32.0 is out, and we're all waiting for the mod update :)

Thanks in advance

**Comment by MOOOOs** [comment]
Yes please update

**Comment by kiren665** [comment]
Yes please
Looking forward to your updates

**Comment by Ferrster** [comment]
[Done!](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.11)

**Comment by TsengoHUN** [comment]
Many thanks!

**Comment by Ferrster** [comment]
> [Done!](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.12)

Oops, posted wrong link. Should be correct now

**Comment by Jakabekokov** [comment]
Hello!

Thanks for your lovely work! The patch just came out today, would you please update your mod?

Thanks!
