### ISSUE TITLE
Update for game version v32.1

### ISSUE THREAD

**Issue by Zeroykaa** [Ferrster/Snowrunner-Manual-Gearbox-Mod#38]
Please update your mod, due to the game update v32.1. A window with an error opens and the mod does not work
<details>

[![Детали][1]][1]
 
[1]: https://github.com/user-attachments/assets/76f19e80-1d18-4d1a-bf59-d937746f63dd
 
</details>

**Comment by RedFoxOKB** [comment]
Yes please update_(:з」∠)_

**Comment by Ferrster** [comment]
[Done!](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.13). Sorry for the delay

**Comment by Jakabekokov** [comment]
Please update the mod to the newest patch.
Amazing work btw 😉

**Comment by Apanovich86** [comment]
please update according to the latest snowrunner game update
