### ISSUE TITLE
Engaging AWD while driving puts the truck into 1st gear. Coming out of highrange does the same.

### ISSUE THREAD

**Issue by Louis-Cyphre** [Ferrster/Snowrunner-Manual-Gearbox-Mod#39]
Both Engaging/disengaging AWD while driving puts the truck into 1st gear.
Also, when coming out of Highrange, 1st is engaged.

It seems just tapping the clutch/lb button will always put the gearbox into 1st,

**Comment by Ferrster** [comment]
Yes, it's a known thing. I'll fix it in the next release and leave it as an option for those who might've depended on such behavior.

**Comment by Ferrster** [comment]
Fixed in [v0.1.14](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.14)
