### ISSUE TITLE
[Open Letter] Thanks!

### ISSUE THREAD

**Issue by MisterNoNameLP** [Ferrster/Snowrunner-Manual-Gearbox-Mod#4]
This is no issue ik, but I just want to say thanks! Im looking for a way to have manual shifting in this game since I started playing it and now we finally have it! Thanks so much for ur work!

Its a shame u dont get all the love from the players directly, but here is a video showcasing ur mod, just take a look at the comments :)

https://www.youtube.com/watch?v=uJvD4ZIp6zM

**Comment by Ferrster** [comment]
Hi! Thanks a lot! Im pleased to hear people find this mod useful, even though it's not ideal.
