### ISSUE TITLE
Update 32.2 

### ISSUE THREAD

**Issue by MOOOOs** [Ferrster/Snowrunner-Manual-Gearbox-Mod#40]
So today new update came out and i guess it broke it again haven't tested. If its broken can you make update so it works again?

**Comment by RedFoxOKB** [comment]
Yes, I have tried the mod, and the game crashed_(:з」∠)_

**Comment by Ferrster** [comment]
[Done!](https://github.com/Ferrster/Snowrunner-Manual-Gearbox-Mod/releases/tag/v0.1.14)

**Comment by RuGOST** [comment]
Работает странно, повышенная и пониженная игнорируется!

**Comment by Saltypilot** [comment]
Приветствую! Специалист по ремонту МКПП, отремонтируй нам коробки пожалуйста для версии 1.594075.SNOW_DLC_14. На тебя одна надежда, ездить не возможно. Благодарю

**Comment by sharkk1244** [comment]
so i installed it correctly and it runs but the moment the mod starts working it crashes my game, i do have about 20 other mods from modio but theyre all trailers and addons for existing trucks

**Comment by MOOOOs** [comment]
Stop commenting on this and reopen new issue
