### ISSUE TITLE
Incompatible with new game update (2023/05/25)

### ISSUE THREAD

**Issue by MisterNoNameLP** [Ferrster/Snowrunner-Manual-Gearbox-Mod#6]
The mod does not work since the update on 2023/05/25.

**Comment by Ferrster** [comment]
Thank you! Working on a fix right now

**Comment by Ferrster** [comment]
Fixed. Should be work now

**Comment by DS300C** [comment]
You deserve a Medal of Honor for this my friend.  And a second one for the turbo update you did right now. Its so sad, that the 100 devs from focus are unable to implement this feature. 
thank you! this takes the game to another level.

**Comment by MisterNoNameLP** [comment]
So true! This mod makes the game so much more enjoyable.
People like you make the world of gaming a better place.
